### ISSUE TITLE
Add support for CommonJS modules

### ISSUE THREAD

**Issue by lotharking** [li0ard/tsemrtd#1]
Right now, this package only works with ES modules (ESM). A lot of Node.js projects and setups still rely on CommonJS (CJS), so adding CJS support would make it easier to use in more projects and environments.

**Comment by li0ard** [comment]
imho, ESM modules are the de-facto standard for TypeScript, and CommonJS support is made for backward compatibility. Many environments (e.g. Node, Bun, Deno and popular browsers) support ESM by default.
